services:
  flask_app1:
    container_name: flask_app1
    image: motov547/student-api:1.0.0
    networks:
      - nginx-network
    ports:
      - "8081:5000"
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:postgrespass@flask_db:5432/postgresdb
    depends_on:
      - flask_db
  flask_app2:
    container_name: flask_app2
    image: motov547/student-api:1.0.0
    networks:
      - nginx-network
    ports:
      - "8082:5000"
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:postgrespass@flask_db:5432/postgresdb
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    networks:
      - nginx-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app1
      - flask_app2
    networks:
      - nginx-network
    ports:
      - "8080:8080"

volumes:
  pgdata: {}

networks:
  nginx-network: