services:
  flask_app:
    container_name: flask_app
    image: motov547/student-api:1.0.1
    # build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:postgrespass@flask_db:5432/postgresdb
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}