name: Docker Image CI pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash
    working-directory: 4-ci-pipeline

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Build API
      run: | 
        make prepare_db
    - name: Run tests
      run: |
        make run_tests
    - name: Run linter
      run: |
        make run_lint
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
